modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/BumbleSoftware/Fastload/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://github.com/BumbleSoftware/Fastload/raw/Forge-1.20.1/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/fastload"
logoFile = "logo.png"
credits = "${credits}"
authors = "${mod_authors}"
displayTest="MATCH_VERSION"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"