modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPL-3.0"

issueTrackerURL="https://github.com/BumbleSoftware/Fastload/issues"

[[mods]]
modId = "fastload"
version = "${version}"
displayName = "Fastload"
updateJSONURL = "https://github.com/BumbleSoftware/Fastload/raw/Forge-1.19.2/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/fastload"
logoFile = "logo.png"
credits = "AbdElAziz, FluffyBumblebees, JoostMSoftware, VidTu, kennytv"
authors = "AbdElAziz"
description = '''
Load your world at lightning speed!
'''

[[dependencies.fastload]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fastload]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
